import type { Metadata } from 'next';
import { Barlow_Semi_Condensed, Inter } from 'next/font/google';
import './globals.css';
import { ApolloContext } from '@/api/apollo-context';

export const metadata: Metadata = {
	title: 'SNEAKLINE',
	icons: '/logo.png',
	description: 'Generated by create next app',
};

const barlow_Semi_Condensed = Barlow_Semi_Condensed({
	subsets: ['latin'],
	display: 'swap',
	weight: ['500', '600', '700', '800'],
	variable: '--font-barlow-semi-condensed',
});

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ApolloContext>
				<body className={`${barlow_Semi_Condensed.variable} ${inter.variable}`}>
					{children}
				</body>
			</ApolloContext>
		</html>
	);
}
